# Generated by Django 2.2.6 on 2020-02-08 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(max_length=30, null=True)),
                ('add', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('birth', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_add', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('rent', models.IntegerField(null=True)),
                ('dist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.District')),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.Register')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.State')),
            ],
        ),
        # #adding new migrations for newly created "pay" table
        # migrations.CreateModel(
        #     name='pay',
        #     fields=[
        #         ('bookid',models.IntegerField(auto_incremented=True,primary_key=True)),
        #         ('trnid',models.IntegerField(null=True)),
        #         ('userid',models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.Register')),
        #         ('date',models.IntegerField(null=True)),
        #         ('ownerid',models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.Owner_Detail')),
        #     ]
        # )


        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, null=True)),
                ('img', models.FileField(null=True, upload_to='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.Owner_Detail')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.State'),
        ),
    ]
