# Generated by Django 2.2.6 on 2020-02-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_detail',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
