# Generated by Django 3.1.10 on 2023-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_auto_20200218_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='proof',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
